---
title: "Demonstration of Clustered Data"
author: "Andy Grogan-Kaylor"
date: '`r Sys.Date()`'
output: 
  distill::distill_article:
    highlight: haddock
    toc: yes
    code_folding: true
  html_document: 
    highlight: haddock
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

```

```{r}

# library(Rcmdr)

library(foreign) # import data

# library(googleVis)

library(lme4) # MLM

library(ggplot2) # beautiful graphs

library(ggthemes) # nice themes

library(plotly) # animated graphs

library(broom)

library(pander) # nice tables

library(sjPlot) # nice tables for MLM

```

```{r}

# get the data sets

group_dataset <- 
  read.dta("demo group.dta", 
           convert.dates=TRUE, convert.factors=TRUE, missing.type=TRUE, 
           convert.underscore=TRUE, warn.missing.labels=TRUE)

individual_dataset <- 
  read.dta("demo individual.dta", 
           convert.dates=TRUE, convert.factors=TRUE, missing.type=TRUE, 
           convert.underscore=TRUE, warn.missing.labels=TRUE)


```

# Grouped and Individual Data

> “The data were generated from random numbers, and there is no relation between X and Y at all.  Firstly, values of X and Y were generated for each ‘subject,’ then a further random number was added to make the individual observation.”

From Bland and Altman, *BMJ*, 1994, 308, 896.

So... we follow their procedure.


## Grouped Data

```{r, eval = TRUE, echo=FALSE}

p1 <- ggplot(group_dataset,
             aes(x = x, y = y, 
                 color = factor(groupnum),
                 label = groupnum)) +
  geom_point(size = 10, show.legend = FALSE) + 
  geom_text(color="white",
            show.legend = FALSE) +
  ggtitle("Grouped Data") +
  theme_minimal() +
  scale_color_viridis_d() +
  # scale_color_brewer(palette = "Set1") +
  xlim(0,100) +
  ylim(-25, 125) +
  theme(legend.position = "none")

ggplotly(p1)

```

## Individual Data

```{r, eval = TRUE, echo=FALSE}

p2 <- ggplot(individual_dataset, 
             aes(x = x.new, y = y.new,
                 color = factor(groupnum),
                 label = groupnum)) +
  geom_point(size = 5, show.legend = FALSE) + 
  geom_text(color="white", 
            show.legend = FALSE) +
  ggtitle("Individual Data") +
  theme_minimal() +
  scale_color_viridis_d() +
  # scale_color_brewer(palette = "Set1") +
  xlim(0,100) +
  ylim(-25, 125) +
  theme(legend.position = "none")

ggplotly(p2)

```

# Analyses

## OLS

```{r}

myOLS <- lm(y.new ~x.new, data = individual_dataset)

# summary(myOLS)

sjPlot::tab_model(myOLS)

# pander(tidy(myOLS))

```

## MLM

```{r}

myMLM <- lmer(y.new ~x.new + (1 | groupnum), 
                              data = individual_dataset)

# summary(myMLM)

sjPlot::tab_model(myMLM)

# pander(tidy(myMLM))

```
